server:
  port: 32228
spring:
  application:
    name: main-service
  cloud:
    config:
      discovery:
        enabled: true
        service-id: valera-config-server
  config:
    import: configserver:valera-config-server
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:32001/eureka}
val:
  test:
    property: Hello from main-server

